services:
  - type: web
    name: alexandria-data-lake-svc
    env: node
    region: oregon
    plan: free
    branch: blueprint
    buildCommand: yarn && yarn build
    startCommand: yarn m:run && yarn start:prod
    autoDeploy: false
    envVars:
      - key: STREAM_HISTORICAL_DATA
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: alexandria-data-lake-db
          property: connectionString
      - key: NODE_VERSION
        value: 16.15.1

databases:
  - name: alexandria-data-lake-db
    plan: free
    ipAllowList: []
